### ISSUE TITLE
AI (Internal): 514 message: "SDK Initialization Failed - In web teams

### ISSUE THREAD

**Issue by abhijith-k07** [OfficeDev/microsoft-teams-library-js#1453]
Hello The teams SDK is failing o initialize in web teams 

browser Tested - Chrome 107.0.5304.107

**Error Message**

AI (Internal): 514 message:"SDK Initialization Failed - no telemetry will be sent: [object Error]{ stack: 'Error: Please provide instrumentation key
    at W (https://teams.microsoft.com.rproxy.goskope.com/statics/hashed/webworker-23c3e56.js:1:276055)
    at h.<computed> (https://teams.microsoft.com.rproxy.goskope.com/statics/hashed/webworker-23c3e56.js:1:295796)
    at Object.initialize (https://teams.microsoft.com.rproxy.goskope.com/statics/hashed/webworker-23c3e56.js:1:272663)
    at e.<computed> (https://teams.microsoft.com.rproxy.goskope.com/statics/hashed/webworker-23c3e56.js:1:299242)
    at Object.initialize (https://teams.microsoft.com.rproxy.goskope.com/statics/hashed/webworker-23c3e56.js:1:272663)
    at https://teams.microsoft.com.rproxy.goskope.com/statics/hashed/webworker-23c3e56.js:1:301543
    at be (https://teams.microsoft.com.rproxy.goskope.com/statics/hashed/webworker-23c3e56.js:1:280699)
    at e.initialize (https://teams.microsoft.com.rproxy.goskope.com/statics/hashed/webworker-23c3e56.js:1:300860)
    at Object.initialize (https://teams.microsoft.com.rproxy.goskope.com/statics/hashed/webworker-23c3e56.js:1:272663)
    at [https://teams.microsoft.com.rproxy.goskope.com/statics/hashed/webworker-23c3e56.js:1:343355'](https://teams.microsoft.com.rproxy.goskope.com/statics/hashed/webworker-23c3e56.js:1:343355%27), message: 'Please provide instrumentation key', name: 'Error'"

**Comment by Prasad-MSFT** [comment]
Hi @abhijith-k07 
Could you please provide the repro steps what you are trying to do?  Could you please verify if you have configured instrumentation key? 
Please refer this doc which explains Troubleshooting SDK load failure for JavaScript web apps
https://learn.microsoft.com/en-us/azure/azure-monitor/app/javascript-sdk-load-failure
https://learn.microsoft.com/en-us/azure/azure-monitor/app/javascript?tabs=snippet
