### ISSUE TITLE
Error: "CancelledByUser" at p (https://res.cdn.office.net/teams-js/2.7.1/js/MicrosoftTeams.min.js:23404)

### ISSUE THREAD

**Issue by yiqing-zhao** [OfficeDev/microsoft-teams-library-js#1798]
Hi Team,

We are currently importing Teams JS in C# project. However the error in step 6 appeared. After testing, the error only appears in Teams on the web, and works fine in Teams Desktop.

You could reproduce the error by following the steps:
1. Install Visual Studio and Microsoft Teams development tools under individual components
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/45935381/0991025e-fd82-492f-b185-6ac22bc3f0e5)

2. Scaffold a new project - Microsoft Teams App - Tab - Configure With SSO.

3. Under Components/Welcome.razor, add `await MicrosoftTeams.InitializeAsync()` as follows
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/45935381/048ec0c2-2f59-4ccb-bd1c-3d45f7239383)

4. Prepare Teams App Dependencies and Press F5 to start local debug
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/45935381/5956b9f1-448c-4e39-9467-f7a0efa18d2d)

5. Click `Authorize` and the Auth page will pop out. Click Accept.
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/45935381/a1409a57-5370-4e96-a353-e2f0f9ed80ae)

6. Error appeared instead of the profile card.
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/45935381/3c2620d6-2c4a-4f9c-bd4d-10ce6d0901bc)

7. Refresh the page, the profile card appeared.
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/45935381/d3f47c0c-957c-4733-9911-f1f9a56ca64a)

**Comment by yiqing-zhao** [comment]
It might be caused by https://github.com/OfficeDev/microsoft-teams-library-js/blob/release/2.11.0/packages/teams-js/src/public/authentication.ts#LL369C18-L369C18, https://github.com/OfficeDev/microsoft-teams-library-js/blob/release/2.11.0/packages/teams-js/src/public/authentication.ts#L293, where the monitor did not shut down for some reason.

**Comment by sayali-MSFT** [comment]
@yiqing-zhao -Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@yiqing-zhao -We are also tried same scenario as mentioned above but not able to repro. when we click Authorize and the Auth page will pop out. Click Accept. then automatically appeared the profile card.

It seems to be like Teams SDK is not initialized properly.

![Screenshot 2023-06-13 155812](https://github.com/OfficeDev/microsoft-teams-library-js/assets/93527375/107da254-5cc5-4403-ae96-8e090a0fd723)

**Comment by yiqing-zhao** [comment]
@sayali-MSFT Are you running in Teams on the web or Teams Desktop? It seems that the error only appears in Teams on the web.

**Comment by sayali-MSFT** [comment]
@yiqing-zhao -Running the teams on Web only.

**Comment by yiqing-zhao** [comment]
This makes the issue a little wierd. Since my colleague and I could both reproduce the error. And the only thing we did was just to add the line `await MicrosoftTeams.InitializeAsync()`.

**Comment by yiqing-zhao** [comment]
@sayali-MSFT Tried again on my end, and the error still appears. Are there any suggestions to check whether SDK is initialized properly?
```
Error: CancelledByUser
    at p (https://res.cdn.office.net/teams-js/2.7.1/js/MicrosoftTeams.min.js:1:23404)
    at https://res.cdn.office.net/teams-js/2.7.1/js/MicrosoftTeams.min.js:1:23085
```

**Comment by sayali-MSFT** [comment]
@yiqing-zhao -We are able to repro that issue, we have raised bug for the same. We will inform you once we get any update.

**Comment by yiqing-zhao** [comment]
Any update?

**Comment by sayali-MSFT** [comment]
@yiqing-zhao - Sorry for delay in response!!
We are actively checking the status of bug with engineering team and let you know the updates, if we have any.

**Comment by yiqing-zhao** [comment]
Hi team, actually I don't think this is caused by TeamsFx, as with same code, Teams desktop could work properly while Teams on the web showed the error. Any possible speculation is helpful to me, thanks!
