### ISSUE TITLE
The library has not been initialized when using NextJS

### ISSUE THREAD

**Issue by RicBruD4S** [OfficeDev/microsoft-teams-library-js#1945]
Hi, I've a NextJS project with several pages (tsx), inside one of these pages I require the context of teams (because the web app is available through Teams as an app which loads the web app URL).
I've placed this code inside the page:
```
...other imports
import * as microsoftTeams from '@microsoft/teams-js';
microsoftTeams.app.initialize().then(()=>{
  console.log("App.js: initializing client SDK initielized");
  microsoftTeams.app.notifyAppLoaded();
  microsoftTeams.app.notifySuccess();
  microsoftTeams.app.getContext().then((context) => {

    console.log("context-----",context);
           
  });
}).catch((error)=>{
  console.error(error);
});
..other exports
```
But when it passes through the code, it gives me this error:
```
App.js: initializing client SDK initielized
Error: The library has not yet been initialized
    at xe (webpack-internal:///(rsc)/./node_modules/@microsoft/teams-js/dist/MicrosoftTeams.min.js:830:55)
    at t.notifyAppLoaded (webpack-internal:///(rsc)/./node_modules/@microsoft/teams-js/dist/MicrosoftTeams.min.js:1375:21)
    at eval (webpack-internal:///(rsc)/./app/page.tsx:24:58)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
```

How can I solve this issue?

PS: I've embedded the app in an app developed using the Developer Portal on Teams. Teams version 1.6.00.24078 (64-bit)

**Comment by Prasad-MSFT** [comment]
@RicBruD4S - Could you please try` async/await` and check if it helps?

```
import * as microsoftTeams from '@microsoft/teams-js';
async function initializeTeams() {
  try {
    await microsoftTeams.app.initialize();
    console.log("App.js: initializing client SDK initialized");
    microsoftTeams.app.notifyAppLoaded();
    microsoftTeams.app.notifySuccess();
    const context = await microsoftTeams.app.getContext();
    console.log("context-----",context);
  } catch (error) {
    console.error(error);
  }
}
initializeTeams();
```

**Comment by RicBruD4S** [comment]
> @RicBruD4S - Could you please try` async/await` and check if it helps?
> 
> ```
> import * as microsoftTeams from '@microsoft/teams-js';
> async function initializeTeams() {
>   try {
>     await microsoftTeams.app.initialize();
>     console.log("App.js: initializing client SDK initialized");
>     microsoftTeams.app.notifyAppLoaded();
>     microsoftTeams.app.notifySuccess();
>     const context = await microsoftTeams.app.getContext();
>     console.log("context-----",context);
>   } catch (error) {
>     console.error(error);
>   }
> }
> initializeTeams();
> ```

Not working, always the same error, library version 2.15.0

**Comment by Prasad-MSFT** [comment]
@RicBruD4S - Did you try downgrading/upgrading the library version and check if it works? When we tested we used `@microsoft/teams-js": "^2.5.0`

**Comment by RicBruD4S** [comment]
Using 2.5.0, it gives the following error:
 ```
○ Compiling /page ...
 ✓ Compiled /page in 22.4s (703 modules)
 ⨯ node_modules\@microsoft\teams-js\dist\MicrosoftTeams.min.js (1:225) @ eval
 ⨯ ReferenceError: self is not defined
    at __webpack_require__ (<path_to_project>\src\.next\server\webpack-runtime.js:33:42)
    at eval (./providers/ms-teams-provider.ts:6:77)
    at (ssr)/./providers/ms-teams-provider.ts (<path_to_project>\src\.next\server\app\page.js:260:1)
    at __webpack_require__ (<path_to_project>\src\.next\server\webpack-runtime.js:33:42)
    at eval (./contexts/auth-context.tsx:12:86)
    at (ssr)/./contexts/auth-context.tsx (<path_to_project>\src\.next\server\app\page.js:205:1)
    at __webpack_require__ (<path_to_project>\src\.next\server\webpack-runtime.js:33:42)
    at eval (./features/providers.tsx:7:80)
    at (ssr)/./features/providers.tsx (<path_to_project>\src\.next\server\app\page.js:238:1)
    at __webpack_require__ (<path_to_project>\src\.next\server\webpack-runtime.js:33:42)
```

**Comment by Prasad-MSFT** [comment]
@RicBruD4S - Could you please ensure that the Teams JS SDK is only imported and used in client-side code? As you're using, you can use dynamic imports to only load the Teams JS SDK on the client side.

**Comment by RicBruD4S** [comment]
Hi, It seems that on NextJS there was an issue, indeed it has been used server side. I am now studying a way to send such information in server side and start a session. Any idea on this ? Thank you.

**Comment by AE-MS** [comment]
Can you elaborate a bit on what you're looking to do? For example, what information are your trying to send server side and start a session?
